#!/usr/bin/env python3
"""
Auto Memory Saver - Full Auto Mode
全主动记忆保存：每次决策后自动保存到记忆系统
"""

import sys
import json
from datetime import datetime
from pathlib import Path
import os

class AutoMemorySaver:
    """
    自动记忆保存器
    功能：
    - 每次决策后自动保存
    - 智能识别重要事件
    - 自动更新 MEMORY.md 和 daily notes
    """
    
    def __init__(self):
        self.workspace = Path.home() / ".openclaw/workspace"
        self.memory_file = self.workspace / "MEMORY.md"
        self.daily_file = self.workspace / "memory" / f"{datetime.now().strftime('%Y-%m-%d')}.md"
        self.history_file = self.workspace / ".memory_history.json"
        
        # 确保目录存在
        (self.workspace / "memory").mkdir(exist_ok=True)
    
    def save_decision(self, decision_type, content, confidence=None, context=None):
        """
        保存决策
        参数:
            decision_type: 决策类型 (LEARNING/CONFIG/DECISION/EVENT)
            content: 决策内容
            confidence: 置信度 (可选)
            context: 上下文信息 (可选)
        """
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")
        
        entry = {
            "timestamp": timestamp,
            "type": decision_type,
            "content": content,
            "confidence": confidence,
            "context": context
        }
        
        # 保存到daily notes
        self._save_to_daily(entry)
        
        # 更新长期记忆
        self._update_memory(entry)
        
        # 保存到历史记录
        self._save_history(entry)
        
        return entry
    
    def _save_to_daily(self, entry):
        """保存到每日笔记"""
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")
        
        content = f"""
### {entry['type']} - {timestamp}

**{entry['content']}**

"""
        if entry['confidence']:
            content += f"- 置信度: {entry['confidence']*100:.0f}%\n"
        
        if entry['context']:
            content += f"- 上下文: {entry['context']}\n"
        
        with open(self.daily_file, 'a', encoding='utf-8') as f:
            f.write(content)
    
    def _update_memory(self, entry):
        """更新长期记忆"""
        if not self.memory_file.exists():
            self._init_memory_file()
        
        # 读取现有内容
        with open(self.memory_file, 'r', encoding='utf-8') as f:
            content = f.read()
        
        # 添加新条目
        new_section = f"""
## {entry['timestamp']} - {entry['type']}

**{entry['content']}**

"""
        if entry['confidence']:
            new_section += f"- 置信度: {entry['confidence']*100:.0f}%\n"
        
        if entry['context']:
            new_section += f"- 上下文: {entry['context']}\n"
        
        # 在第一个标题前插入，或追加到末尾
        if "## " in content:
            first_header = content.find("## ")
            new_content = content[:first_header] + new_section + "\n" + content[first_header:]
        else:
            new_content = content + new_section
        
        with open(self.memory_file, 'w', encoding='utf-8') as f:
            f.write(new_content)
    
    def _save_history(self, entry):
        """保存到历史记录"""
        history = []
        if self.history_file.exists():
            with open(self.history_file, 'r') as f:
                history = json.load(f)
        
        history.append(entry)
        
        # 只保留最近100条
        history = history[-100:]
        
        with open(self.history_file, 'w') as f:
            json.dump(history, f, ensure_ascii=False, indent=2)
    
    def _init_memory_file(self):
        """初始化MEMORY.md"""
        with open(self.memory_file, 'w', encoding='utf-8') as f:
            f.write("""# MEMORY.md - Your Long-Term Memory

*Auto-generated by Auto Memory Saver*

---

## How to Use

This file stores your permanent memories:
- Important decisions
- Learned patterns
- Configuration changes
- Key events

---

""")
    
    def auto_save_from_cognition(self, result):
        """从认知框架结果自动保存"""
        if result['confidence'] >= 0.80:
            self.save_decision(
                decision_type="DECISION",
                content=f"执行任务: {result['intent']['type']}",
                confidence=result['confidence'],
                context=f"置信度 {result['confidence']*100:.0f}%"
            )
            return True
        return False
    
    def save_learning(self, topic, insight):
        """保存学习"""
        self.save_decision(
            decision_type="LEARNING",
            content=f"学习: {topic}",
            context=insight
        )
    
    def save_config(self, config_name, old_value, new_value):
        """保存配置变更"""
        self.save_decision(
            decision_type="CONFIG",
            content=f"配置变更: {config_name}",
            context=f"{old_value} → {new_value}"
        )


def main():
    """测试"""
    saver = AutoMemorySaver()
    
    print("🧠 自动记忆保存器测试")
    print("=" * 50)
    
    # 测试保存决策
    entry = saver.save_decision(
        decision_type="TEST",
        content="测试自动保存功能",
        confidence=0.95,
        context="测试环境"
    )
    
    print(f"\n✅ 已保存:")
    print(f"   类型: {entry['type']}")
    print(f"   时间: {entry['timestamp']}")
    print(f"   内容: {entry['content']}")
    print(f"   置信度: {entry['confidence']*100:.0f}%")
    
    print(f"\n📁 保存位置:")
    print(f"   每日笔记: {saver.daily_file}")
    print(f"   长期记忆: {saver.memory_file}")


if __name__ == "__main__":
    main()
